//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GURPS_GEN.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GURPS_GEN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --Flexible Materials--
        ///Linen [0,85] $8,3 F/O 
        ///TL6+ Linen [0,85] $0,57 F/O 
        ///Rubber [0,45] $5 14 7 C, F, S* F/O !Cut/Pi! *3*
        ///Elastic Polymer [0,16] $100 ($50 at TL8+) 16 8 F F/O !Cut/Pi! *3*
        ///TL8+ Elastic Polymer [0,16] $50  16 8 F F/O !Cut/Pi! *3*
        ///Nomex [0,066] $50 ($25 at TL8+) 10 5 F† F/O !!Fire!! *10* 
        ///TL8+ Nomex [0,066] $25 10 5 F† F/O !Fire! *10* 
        ///Nylon [0,5] $256 3 F F/O !Cut/Pi! *3*
        ///TL8+ Nylon [0,5] $6 6 3 F F/O !Cut/Pi! *3*
        ///Ballistic Polymer [0,06] $200 48 24 F‡ F/O !Cut/Pi! *3*
        ///TL9+ Ballis [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Armor_table {
            get {
                return ResourceManager.GetString("Armor_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Types Flexible
        ///============
        ///Fabric [1] $1 &amp;1 F/O TL 1+ &lt;&gt;
        ///TL 6+ Optimized Fabric [0,8] $2 &amp;2 F/O &lt;&gt;
        ///
        ///Types Rigid/solid
        ///============
        ///Scales [1,1] $0,8 &amp;2 R/S TL 9+ &lt;-1 DR vs, crushing unless armor is DR 4+&gt;
        ///TL 9+ Solid [1] $1 &amp;2  Solid &lt;&gt;
        ///
        ///TL 9+ Segmented Plate [1,45] $0,9 &amp;3 R/S &lt;&gt;
        ///TL 1-9 Segmented Plate [1,45] $1,5 &amp;3 R/S &lt;&gt;
        ///
        ///TL 1-9 Plate [0,8] $5 &amp;3 R/S &lt;&gt;
        ///TL 9+ Plate [0,8] $1,5 &amp;3 R/S &lt;&gt;
        ///
        ///TL Chainmail [0,7] $3,5 &amp;2 R/S &lt;&gt;
        ///
        ///TL 6+ Impact-Absorbing [0.65] $5   &amp;2 R/S  &lt;Half DR vs. damage t [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Armor_type {
            get {
                return ResourceManager.GetString("Armor_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon knight_shield_icon_125592 {
            get {
                object obj = ResourceManager.GetObject("knight_shield_icon_125592", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///=====!Universal!======
        /// Empty slot [1] $0 &amp;0 ++0 &lt;&gt; //Пустая строка !Universal!
        ///=========!Universal! Enchants========
        ///=!Universal! Fortify===
        ///Fortify 1 [1] $0 &amp;1 ++50 &lt;зачарован слабым укреплением&gt; !Universal!
        ///Fortify 2 [1] $0 &amp;2 ++6600 &lt;зачарован укреплением&gt; !Universal!
        ///Fortify 3 [1] $0 &amp;3 ++26400 &lt;зачарован сильным укреплением&gt; !Universal!
        ///Fortify 4 [1] $0 &amp;4 ++99000 &lt;зачарован мастерским укреплением&gt; !Universal!
        ///Fortify 5 [1] $0 &amp;5 ++264000 &lt;зачарован божественным укреплением&gt; !Universal!
        ///=!U [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Other_stuff {
            get {
                return ResourceManager.GetString("Other_stuff", resourceCulture);
            }
        }
    }
}
